import { Request } from 'express';

export interface IUser {
  _id?: string;
  name: string;
  email: string;
  password?: string; // Optional for OAuth users
  phone?: string; // Optional for OAuth users
  googleId?: string;
  facebookId?: string;
  role: 'user' | 'admin' | 'vendor' | 'driver';
  isActive: boolean;
  // Vendor-specific fields
  businessName?: string;
  businessType?: 'car_rental' | 'taxi_service' | 'bus_service' | 'truck_service' | 'other';
  businessLicense?: string;
  businessAddress?: string;
  // Driver-specific fields
  licenseNumber?: string;
  licenseExpiry?: Date;
  vehicleType?: 'car' | 'suv' | 'van' | 'bus' | 'truck' | 'bike';
  experience?: number;
  rating?: number;
  isAvailable?: boolean;
  // Common fields for vendors and drivers
  bankDetails?: {
    accountNumber?: string;
    ifscCode?: string;
    accountHolderName?: string;
  };
  documents?: {
    aadhar?: string;
    pan?: string;
    license?: string;
    vehicleRC?: string;
    insurance?: string;
  };
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IBooking {
  _id?: string;
  orderId?: string; // Unique order ID generated by system
  userId: string;
  sourcePlatform?: 'phone' | 'email' | 'whatsapp' | 'website' | 'facebook' | 'instagram' | 'linkedin' | 'mobile_app' | 'direct_office';
  serviceType: 'person' | 'goods';
  serviceCategory: string;
  email: string;
  pickupLocation: string;
  dropLocation: string;
  pickupDate: Date;
  pickupTime: string;
  dropDate?: Date;
  dropTime?: string;
  numberOfPersons?: number;
  goodsDescription?: string;
  vehicleType?: string;
  driverRequired?: boolean;
  orderStatus: 'primary' | 'updated' | 'quotation_shared' | 'confirmed' | 'in_progress' | 'pending_payment' | 'completed' | 'pending_feedback' | 'cancelled';
  status: 'pending' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled'; // Legacy status for backward compatibility
  totalAmount: number;
  paymentStatus: 'pending' | 'paid' | 'failed';
  paymentMethod?: string;
  specialInstructions?: string;
  // Vendor and driver assignment
  assignedVendor?: string;
  assignedDriver?: string;
  vehicleId?: string;
  // Related documents
  quotationId?: string;
  salesOrderId?: string;
  purchaseOrderId?: string;
  invoiceId?: string;
  billId?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IService {
  _id?: string;
  name: string;
  category: 'person' | 'goods';
  description: string;
  basePrice: number;
  pricePerKm?: number;
  isActive: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IVehicle {
  _id?: string;
  name: string;
  type: string;
  capacity: number;
  licensePlate: string;
  isAvailable: boolean;
  driverId?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface IDriver {
  _id?: string;
  name: string;
  licenseNumber: string;
  phone: string;
  email: string;
  isAvailable: boolean;
  rating: number;
  experience: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface AuthRequest extends Request {
  user?: any;
}

export interface ApiResponse<T = any> {
  success: boolean;
  message: string;
  data?: T;
  error?: string;
}

// Timeline/Activity Log
export interface ITimeline {
  _id?: string;
  bookingId: string;
  orderId?: string;
  action: string; // e.g., "Order Created", "Status Updated", "Quotation Shared"
  description: string;
  updatedBy: string; // User ID or system
  updatedByRole?: 'admin' | 'user' | 'vendor' | 'driver' | 'system';
  previousValue?: any;
  newValue?: any;
  metadata?: Record<string, any>;
  createdAt?: Date;
}

// Quotation
export interface IQuotation {
  _id?: string;
  quotationNumber: string; // Unique quotation number
  bookingId: string;
  orderId?: string;
  customerId: string;
  providerId?: string; // Vendor/Service Provider ID
  items: Array<{
    description: string;
    quantity?: number;
    unitPrice: number;
    total: number;
  }>;
  subtotal: number;
  taxes?: number;
  discount?: number;
  totalAmount: number;
  termsAndConditions?: string;
  validUntil: Date;
  status: 'draft' | 'sent' | 'approved' | 'expired' | 'rejected';
  sentAt?: Date;
  approvedAt?: Date;
  approvedBy?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

// Sales Order
export interface ISalesOrder {
  _id?: string;
  salesOrderNumber: string; // Unique SO number (e.g., SO-2024-001)
  bookingId: string;
  orderId?: string;
  quotationId?: string;
  customerId: string;
  items: Array<{
    description: string;
    quantity?: number;
    unitPrice: number;
    total: number;
  }>;
  subtotal: number;
  taxes?: number;
  discount?: number;
  totalAmount: number;
  advanceAmount: number;
  balanceAmount: number;
  status: 'draft' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled';
  createdAt?: Date;
  updatedAt?: Date;
}

// Purchase Order
export interface IPurchaseOrder {
  _id?: string;
  purchaseOrderNumber: string; // Unique PO number (e.g., PO-2024-001)
  bookingId: string;
  orderId?: string;
  salesOrderId?: string;
  providerId: string; // Vendor/Service Provider ID
  items: Array<{
    description: string;
    quantity?: number;
    unitPrice: number;
    total: number;
  }>;
  subtotal: number;
  taxes?: number;
  totalAmount: number;
  advanceAmount: number;
  balanceAmount: number;
  status: 'draft' | 'sent' | 'acknowledged' | 'in_progress' | 'completed' | 'cancelled';
  acknowledgedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

// Financial Transaction
export interface IFinancialTransaction {
  _id?: string;
  transactionNumber: string;
  bookingId: string;
  orderId?: string;
  transactionType: 'customer_advance' | 'customer_balance' | 'customer_refund' | 'provider_advance' | 'provider_balance' | 'provider_refund';
  amount: number;
  paymentMethod: 'cash' | 'bank_transfer' | 'upi' | 'card' | 'cheque' | 'other';
  paymentReference?: string; // UPI ref, transaction ID, cheque number, etc.
  receiptNumber?: string;
  receiptUrl?: string; // Link to uploaded receipt
  description?: string;
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  transactionDate: Date;
  createdBy: string;
  createdAt?: Date;
  updatedAt?: Date;
}

// Invoice
export interface IInvoice {
  _id?: string;
  invoiceNumber: string; // Unique invoice number (e.g., INV-2024-001)
  bookingId: string;
  orderId?: string;
  salesOrderId: string;
  customerId: string;
  items: Array<{
    description: string;
    quantity?: number;
    unitPrice: number;
    total: number;
  }>;
  subtotal: number;
  taxes?: number;
  discount?: number;
  totalAmount: number;
  advancePaid: number;
  balanceDue: number;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  dueDate: Date;
  paidAt?: Date;
  sentAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

// Bill
export interface IBill {
  _id?: string;
  billNumber: string; // Unique bill number (e.g., BILL-2024-001)
  bookingId: string;
  orderId?: string;
  purchaseOrderId: string;
  providerId: string;
  items: Array<{
    description: string;
    quantity?: number;
    unitPrice: number;
    total: number;
  }>;
  subtotal: number;
  taxes?: number;
  totalAmount: number;
  advancePaid: number;
  balanceDue: number;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  dueDate: Date;
  paidAt?: Date;
  sentAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

// Document
export interface IDocument {
  _id?: string;
  bookingId: string;
  orderId?: string;
  documentType: 'receipt' | 'acknowledgement' | 'slip' | 'invoice' | 'bill' | 'quotation' | 'sales_order' | 'purchase_order' | 'other';
  documentName: string;
  fileName: string;
  fileUrl: string; // URL to stored document
  fileSize?: number;
  mimeType?: string;
  uploadedBy: string;
  description?: string;
  isPhysicalCopy: boolean; // Whether physical copy exists
  physicalCopyLocation?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

// Feedback
export interface IFeedback {
  _id?: string;
  bookingId: string;
  orderId?: string;
  feedbackFrom: 'customer' | 'provider';
  feedbackFromId: string; // Customer ID or Provider ID
  rating: number; // 1-5
  comment?: string;
  categories?: {
    service?: number;
    communication?: number;
    punctuality?: number;
    vehicle?: number;
    driver?: number;
  };
  status: 'pending' | 'submitted' | 'reviewed';
  submittedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
} 